# fly.toml
app = "oakframer-site"

[build]
 builder = "heroku/builder:paketo-20"

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = "true"

[deploy]
  release_command = "bin/rails db:prepare"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
