app = "oakframer-site" # or your actual Fly.io app name

primary_region = "lhr" # or closest to you (e.g., ams, fra, iad)

[build]
  dockerfile = "Dockerfile"

[env]
  RAILS_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
