version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          RAILS_ENV: production
    working_directory: ~/app

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout

      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            echo 'export PATH="$HOME/.yarn/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Install Ruby dependencies
          command: |
            gem install bundler -v 2.4.10
            bundle _2.4.10_ install --jobs=4 --retry=3

      - run:
          name: Install JS dependencies
          command: yarn install

      - run:
          name: Build JavaScript assets
          command: yarn build

      - run:
          name: Precompile Rails assets
          command: bundle exec rails assets:precompile

  deploy:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Install Fly.io CLI
          command: |
            curl -L https://fly.io/install.sh | sh
            echo 'export FLYCTL_INSTALL="$HOME/.fly"' >> $BASH_ENV
            echo 'export PATH="$FLYCTL_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Deploy to Fly.io
          command: |
            source $BASH_ENV
            fly auth token "$FLY_API_TOKEN"
            fly deploy --remote-only

workflows:
  version: 2
  deploy_on_push:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
